Update spec fields in ReadOne post_set_output hook
aws-controllers-k8s/elasticache-controller pull request #29
Opened 2021-05-24 23:58 UTC by echen-98

Description of changes:
Related to https://github.com/aws-controllers-k8s/elasticache-controller/pull/22

To recap, in order to trigger the `Update` code, there needs to be a Spec difference between `desired` and `latest`. The generated `ReadOne` code often doesn't update `latest.Spec` with the latest observed state, since determining the latest observed state often requires some processing or additional API calls. There are many fields this applies to, but this PR starts with `ReplicasPerNodeGroup` and `EngineVersion`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-05-25 15:16 UTC, jaypipes requested changes
Couple minor things, please see inline.

2021-05-25 15:16 UTC, jaypipes commented on pkg/resource/replication_group/post_set_output.go
> +	ko *svcapitypes.ReplicationGroup,
recommend just passing a `*resource` and do the `ko` unpacking inside the function. That way you don't need to import the `svcapitypes` package.

2021-05-25 15:16 UTC, jaypipes commented on pkg/resource/replication_group/custom_update_api.go
> +	latestCacheCluster, err := rm.describeCacheCluster(ctx, latest.ko)
This change seems unnecessary... why not just keep the describeCacheCluster function signature the same and "unpack" the `ko` field from within the function body?

2021-05-25 15:16 UTC, jaypipes commented on pkg/resource/replication_group/custom_update_api.go
> +	latest *resource,
:+1: the above is how all these function signatures should be structured.

2021-05-25 15:16 UTC, jaypipes commented on pkg/resource/replication_group/post_set_output.go
> +	ko *svcapitypes.ReplicationGroup,
same comment as above.

2021-05-25 15:16 UTC, jaypipes commented on pkg/resource/replication_group/post_set_output.go
> +	"github.com/aws/aws-sdk-go/service/elasticache"
recommend aliasing this package as `svcsdk` as we do elsewhere in all the `pkg/resource` templates:

https://github.com/aws-controllers-k8s/code-generator/blob/cf8f94fd9835b500cbf736fcea48efe0ca37f8a1/templates/pkg/resource/sdk.go.tpl#L13

It's easier to always use this alias and by using the alias, you allow readers of the code to imagine how this code might be used in other service-specific controllers.

2021-05-26 17:03 UTC, echen-98 commented
@jaypipes thanks for the comments. Changes made as requested

2021-05-26 17:23 UTC, jaypipes approved these changes
:+1:

2021-05-26 17:23 UTC, jaypipes commented
/ok-to-test

2021-06-15 17:03 UTC, kumargauravsharma approved these changes

2021-06-15 18:28 UTC, merged